### ISSUE TITLE
Hi, Do you provide the sourcecode of training scripts now?

### ISSUE THREAD

**Issue by gogo03** [prip-lab/MSU-LatentAFIS#8]
You've done a excellent job!

**Comment by isgursoy** [comment]
Yes @luannd @ctymoszek excellent job, and yes the training code would be nice to see how it does with different datasets.

**Comment by ctymoszek** [comment]
@gogo03 @isgursoy The researchers who worked on this project have since moved on and are no longer maintaining the software. I have updated the accompanying documentation to reflect this. Feel free to build upon or modify it for your own purposes, but please understand that it is provided as-is with no additional warranty.
